server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/votacao_assembleia
spring.datasource.username=votacao
spring.datasource.password=votacao

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
